USE [BarTechImis]
GO

DECLARE	@return_value int,
		@ID int,
		@GUID varchar(50)

EXEC	@return_value = [dbo].[SP_SalesOrder_Insert]
		@ID = @ID OUTPUT,
		@Code = '',
		@GUID = @GUID OUTPUT,
		@Company = 1,
		@SerialNo = '',
		@PaperNo = '',
		@Branch = 1,
		@OrderType = N'01001-105C50CF-8CC5-4627-82B5-80DD3E660189',
		@OrderDate = N'2020-10-20',
		@BranchID = '1',
		@CustomerID = N'01001-D808105D-C2D1-450E-AB8F-446478FC7313',
		@PaymentTermsDue = 0,
		@PaymentTermsAllowCash = 0,
		@PaymentTermsAllowCheque = 0,
		@PaymentTermsAllowBankTrans = 0,
		@PaymentTermsAllowPromiseNote = 0,
		@PaymentTermsAllowCreditCard = 0,
		@PaymentTermsInAdvancePayment = 0,
		@PaymentTermsInAdvanceType = 0,
		@PaymentTermsInAdvanceValue = 0,
		@PaymentTermsInstallment = 0,
		@CurrenceyID = '01001-D0DA0215-C43C-40F7-B63C-D0F46447DA7C',
		@CurrenceyRate = 1,
		@TaxID = '',
		@WareHouseID = '',
		@DiscountProfile = '',
		@DiscountPercent = 0,
		@ValidUpTo = '2021-10-21',
		@ShippingTermsID = '',
		@ShippingTypeID = '',
		@ShippingMethodID = '',
		@ShippingShipperID = '',
		@ShippingDate = '',
		@ShippingDeliveryDate = '',
		@ShippingPortID = '',
		@RFPNo = '',
		@RFPDate = '',
		@RFPSubject = '',
		@ApprovalByID = '',
		@ApprovalDate = NULL,
		@Hold = 0,
		@DownPaymentLink = '',
		@DownPaymentNo = '',
		@DownPaymentValue = 0,
		@TotalValue = 0,
		@TaxValue = 0,
		@ExpencesValue = 0,
		@DiscountValue = 0,
		@NetValue = 0,
		@SaleAccountID = '',
		@SaleJournalID = '',
		@SaleProjectID = '',
		@SaleDepartmentID = '',
		@SaleBudgetID = '',
		@SaleCostID = '',
		@InventoryAccountID = '',
		@InventoryJournalID = '',
		@InventoryProjectID = '',
		@InventoryDepartmentID = '',
		@InventoryBudgetID = '',
		@InventoryCostID = '',
		@SalesManID = '',
		@IsFirmed = '',
		@ConfirmationLevel = 0,
		@Notes = '',
		@DetailLine1 = '',
		@DetailLine2 = '',
		@DetailLine3 = '',
		@DetailLine4 = '',
		@DetailLine5 = '',
		@DetailLine6 = '',
		@DetailLine7 = '',
		@DetailLine8 = '',
		@DetailLine9 = '',
		@DetailLine10 = '',
		@CreatedBy = 1,
		@CreatedMacNo = 0,
		@Printed = 0

SELECT	@ID as N'@ID',
		@GUID as N'@GUID'

SELECT	'Return Value' = @return_value

GO
